import sqlite3 as db

conn = db.connect("naijainfive.db")

print("opened database successfully")
    
conn.execute("CREATE TABLE IF NOT EXISTS Feedback(Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Email TEXT NOT NULL, Message TEXT NOT NULL, DateCreated DATETIME2 NOT NULL)");
conn.execute("CREATE TABLE IF NOT EXISTS NewsPaper(Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, URL TEXT NOT NULL, SCRAPERSRC TEXT NOT NULL, DateCreated DATETIME2 NOT NULL)");
conn.execute("CREATE TABLE IF NOT EXISTS DigitalFile(Id INTEGER PRIMARY KEY AUTOINCREMENT, TheFile BLOB NOT NULL, TypeId INT NOT NULL, Name TEXT NOT NULL, Extension TEXT NOT NULL, ContentType TEXT NOT NULL, IsActive BOOLEAN NOT NULL, DateCreated DATETIME2 NOT NULL)");
conn.execute("CREATE TABLE IF NOT EXISTS CoverPage(Id INTEGER PRIMARY KEY AUTOINCREMENT, NewsPaperId INT NOT NULL, DigitalFileId INT NOT NULL, CoverPageDate DATETIME2 NOT NULL, IsActive BOOLEAN NOT NULL, DateCreated DATETIME2 NOT NULL)");


conn.close()